;MAHDI ZAHIN
.MODEL SMALL
.STACK 100H
.DATA
.CODE
MAIN PROC
    
    MOV AH,1 ;TAKING INPUT
    INT 21H ;EXECUTING INPUT
    
    MOV AH,2 ;SHOWING OUTPUT
    MOV DL,AL
    INT 21H ;EXECUTING OUTPUT
    
    
    MOV AH,4CH
    INT 21H
    
    MAIN ENDP
END MAIN