.MODEL
.STACK 100H
.DATA 
VER DB "SHOW $"
.CODE

MAIN PROC  
    
    MOV AX,@DATA       ;INITIALIZATION OF DATA SEGMENT
    MOV DS,AX
    
    LEA DX,VER           ;LOAD EFFECTIVE ADDRESS
    MOV AH,9
    INT 21H
    
    MOV AH,4CH
    INT 21H
    
    MAIN ENDP
END MAIN